name: VTB API CHECK
run-name: ${{ github.actor }} launched pipeline on ${{ github.ref}}
on: [push]

jobs:
  formatter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: denoland/setup-deno@v2
      - name: run formatter
        run: deno fmt --check
  linter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: denoland/setup-deno@v2
      - name: run linter
        run: deno lint
